### PR TITLE
Feature/squidvip2

### PR DESCRIPTION
**Pull request by gellner**
(Tested with Feature/squidvip2 in openshift-heat - implements keystone_v3 and ocp_branding to fastforward v3.11 branch)

- Adds cor5-2 to the proxy exceptions so that multinetwork works on that OpenStack 
- Implements an extra keepalived VRRP instance to implement squid_vip
- Changes openshift ansible hosts settings to use that new squid_vip
- Altered keepalived config to ensure that each pair of loadbalancers use unique vrrp ids.
- ps and grep are used to check for squid monitoring because the kill -0 method doesn't work!

### CODE REVIEW

**Review by k8soneill — APPROVED** [review]
Approved pending name change discussed on call

**Comment by gellner** [comment]
@stevemul @benbacon This one should be ready to approve/merge now.

**Comment by gellner** [comment]
I made one more tweak because the hardcoded MTU caused connectivity issues in cor5-2 (where the MTU on the ovs interfaces becomes 8900; I've checked that this also works in an OSP10 environment, keeping the 1446 interface MTU which is needed in those environments.

Please approve this and the equivalent branch in openshift-heat, @stevemul & @benbacon

**Review by stevemul — APPROVED** [review]
LGTM

**Pull request merged**
