### PR TITLE
replace deprecated 'include' statements'

### PR DESCRIPTION
**Pull request by andywis**
I replaced all the deprecated "include" statements. 

There are still some in the 3rd party openshift-ansible playbook code that I can't change (but they're dealt with here: https://github.com/openshift/openshift-ansible/issues/5586)

### CODE REVIEW

**Comment by stevemul** [comment]
Looks good to me. We need a way to indicate whether its passed the pipeline tests too - that'll save me asking everytime in a comment! But for now, has it passed the tests?

**Comment by andywis** [comment]
Test run 197 succeeded.

**Comment by andywis** [comment]
part of issue #17

**Review by stevemul — APPROVED** [review]
Looks good to me

**Pull request merged**
