### PR TITLE
Feature/portworx changes

### PR DESCRIPTION
**Pull request by gellner**
Changes to make the necessary changes to node_groups (nodeIPs) and the change to the default squid proxy whitelist which are necessary to install portworx. These changes are designed to cause no change if "deploy_portworx_storage" is set to false or omitted.

Also includes an unrelated minor tweak to disable cert expiry check during upgrades (CNAP-971) since the default behaviour is to fail if certs expire in under a year.

### CODE REVIEW

**Comment by gellner** [comment]
Tested in four deployements:

- Portworx non-net2
- Portworx net2
- non-Portworx non-net2
- non-Portworx net2

**Review by k8soneill — APPROVED** [review]
LGTM

**Review by benbacon — CHANGES_REQUESTED** [review]
Regarding the Portworx  Squid whitelist entries - can we make these more specific? Previously we've attempted to not whitelist entire container registries as this reduces the purpose of the proxy somewhat. I suppose these could be removed post-deployment but wouldn't need to be if we could restrict these solely to Portworx endpoints

**Comment by gellner** [comment]
> 
> 
> Regarding the Portworx Squid whitelist entries - can we make these more specific? Previously we've attempted to not whitelist entire container registries as this reduces the purpose of the proxy somewhat. I suppose these could be removed post-deployment but wouldn't need to be if we could restrict these solely to Portworx endpoints

I will redeploy to check but I'm pretty sure they are minimal unless we have a way of predicting the random string in front of cloudfront, gcr etc

**Comment by gellner** [comment]
@benbacon - the only line that could be made more specific is replacing cloudfront with d3uo42mtx6z2cr.cloudfront.net but that one is likely to change on the next release. 

I guessing to enable squid to do HTTPS whole-URL filtering, it would need to have a dummy-root CA to intercept traffic and quite a complex config?

How do we want to proceed? The only way to make the entries removable after deployment would be to set an imagetag version and setting ImagePullPolicy to never, and then remember to readd the entries to do upgrades? Otherwise, when a container dies due to node maintenance, it won't redeploy.

**Comment by benbacon** [comment]
This branch has now been used to deploy non-Portworx environments, mixed net2/internet Portworx environments and pure net2 Portworx environments

**Review by benbacon — APPROVED** [review]
Looks good

**Comment by k8soneill** [comment]
This is being re-tested and I've created a new branch that will add in cloudsnap creds. That PR will override this one.

**Pull request closed without merging**
