### PR TITLE
Added tests for exposing a service and validating its route.

### PR DESCRIPTION
**Pull request by dbrennand**
This PR adds a two small tests to expose a service and verify the route can be accessed; returning status code 200.

### CODE REVIEW

**Review by k8soneill — CHANGES_REQUESTED** [review]
http://os-sample-python-test-container."{{server}}" won't give you the correct URL. Need to use {{ domainSuffix}} but will need to add -i openshift-ansible-hosts to the ansible line in the pipeline repo

**Comment by dbrennand** [comment]
Pipeline tested and successful. Ready for merge. 👍

**Review by k8soneill — APPROVED** [review]
LGTM

**Review by gellner — APPROVED** [review]
LGTM

**Pull request merged**
